vim.keymap.set("c", "jk", "<esc>", { desc = "jk escaping" })
vim.keymap.set("i", "jk", "<esc>", { desc = "jk escaping" })
vim.keymap.set("v", "jk", "<esc>", { desc = "jk escaping" })
vim.keymap.set("n", "<Up>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("n", "<Down>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("n", "<Left>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("n", "<Right>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Up>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Down>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Left>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Right>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Up>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Down>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Left>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Right>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.del({ "n", "t" }, "<C-h>")
vim.keymap.del({ "n", "t" }, "<C-j>")
vim.keymap.del({ "n", "t" }, "<C-k>")
vim.keymap.del({ "n", "t" }, "<C-l>")
