vim.keymap.set("c", "jk", "<esc>", { desc = "jk escaping" })
vim.keymap.set("i", "jk", "<esc>", { desc = "jk escaping" })
vim.keymap.set("v", "jk", "<esc>", { desc = "jk escaping" })
vim.keymap.set("n", "<Up>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("n", "<Down>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("n", "<Left>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("n", "<Right>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Up>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Down>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Left>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("i", "<Right>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Up>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Down>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Left>", "<Nop>", { desc = "arrow key retraining" })
vim.keymap.set("v", "<Right>", "<Nop>", { desc = "arrow key retraining" })

vim.keymap.del({ "n", "x" }, "gw", { desc = "Search word under cursor" })

local wk = require("which-key")
wk.register({
    ["<leader>Z"] = { "<cmd>Telescope zoxide list<CR>", "Change Directory" },
})
wk.register({ ["<leader><tab>c"] = { "<cmd>TCD<CR>", "Change Tab Directory" } })
wk.register({ ["<leader>wc"] = { "<cmd>WCD<CR>", "Change Window Directory" } })
wk.register({ ["<leader>ua"] = { "<cmd>Alpha<CR>", "Dashboard" } })
